import streamlit as st
import torch
import torchaudio
import os
import tempfile
import argbind
from pathlib import Path

# Vampnet / Audiotools imports
import audiotools as at
from audiotools import AudioSignal
from vampnet.interface import Interface

# Configure Streamlit page
st.set_page_config(
    page_title="VampNet Streamlit",
    page_icon="🧛",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Configuration and Model Loading
@st.cache_resource(show_spinner="Loading VampNet Model...")
def load_vampnet_model():
    """
    Loads the VampNet interface securely and caches it across Streamlit reruns.
    Reads from default checkpoints or environment variables if deployed.
    """
    # Initialize argbind for VampNet's internal argument parser
    argbind.parse_args()
    
    # We default to the standard pretrained model if available,
    # or you can override the codec/model path here.
    interface = Interface.core()
    
    # Push model to GPU if available
    if torch.cuda.is_available():
        interface.to("cuda")
    
    return interface

def process_audio(interface, audio_file, target_duration, loop_mode, num_steps, temperature):
    """
    Core production inference function for VampNet
    """
    with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as fp:
        fp.write(audio_file.read())
        temp_path = fp.name

    try:
        # Load audio signal via descript-audiotools
        signal = AudioSignal(temp_path)
        
        # Ensure it matches VampNet's expected sample rate
        signal.resample(interface.codec.sample_rate)
        if signal.num_channels > 1:
            signal.to_mono()

        # Generate audio using the vampnet interface
        with torch.no_grad():
            output_signal = interface.vamp(
                signal=signal,
                duration=target_duration,
                num_steps=num_steps,
                temperature=temperature,
                return_signal=True,
                loop=loop_mode
            )
            
        # Save output to a temporary file
        out_temp = tempfile.NamedTemporaryFile(delete=False, suffix=".wav")
        output_signal.write(out_temp.name)
        return out_temp.name
        
    finally:
        # Cleanup input temp file
        if os.path.exists(temp_path):
            os.remove(temp_path)

def main():
    st.title("🧛 VampNet: Generative Audio Looping & Variations")
    st.markdown("Upload an audio sample and let VampNet extend, loop, or creatively modify it.")

    try:
        interface = load_vampnet_model()
    except Exception as e:
        st.error(f"Failed to load VampNet model. Ensure checkpoints are correctly downloaded. Error: {str(e)}")
        st.stop()

    # Sidebar parameters
    with st.sidebar:
        st.header("Generation Parameters")
        target_duration = st.slider("Target Duration (seconds)", min_value=1.0, max_value=30.0, value=10.0, step=0.5)
        num_steps = st.slider("Number of Denoising Steps", min_value=10, max_value=150, value=50, step=5)
        temperature = st.slider("Temperature (Creativity)", min_value=0.1, max_value=2.0, value=1.0, step=0.1)
        loop_mode = st.checkbox("Loop Mode (Create a seamless loop)", value=False)
        
        st.markdown("---")
        st.info("VampNet uses masked acoustic token modeling to generate new audio variations.")

    # Main UI
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Input Audio")
        audio_file = st.file_uploader("Upload an audio file (WAV/MP3)", type=['wav', 'mp3', 'flac', 'ogg'])
        
        if audio_file is not None:
            st.audio(audio_file)

    with col2:
        st.subheader("Output Audio")
        generate_btn = st.button("Generate Audio 🚀", type="primary", use_container_width=True)
        
        if generate_btn:
            if audio_file is None:
                st.warning("Please upload an input audio file first.")
            else:
                with st.spinner("VampNet is generating..."):
                    try:
                        output_file_path = process_audio(
                            interface=interface,
                            audio_file=audio_file,
                            target_duration=target_duration,
                            loop_mode=loop_mode,
                            num_steps=num_steps,
                            temperature=temperature
                        )
                        
                        # Read the generated bytes and display the audio player
                        with open(output_file_path, "rb") as fp:
                            audio_bytes = fp.read()
                            
                        st.success("Generation Complete!")
                        st.audio(audio_bytes, format='audio/wav')
                        
                        st.download_button(
                            label="Download Output WAV",
                            data=audio_bytes,
                            file_name="vampnet_output.wav",
                            mime="audio/wav",
                            use_container_width=True
                        )
                        
                        # Cleanup output
                        os.remove(output_file_path)
                        
                    except Exception as e:
                        st.error(f"An error occurred during generation: {str(e)}")

if __name__ == "__main__":
    main()
