import streamlit as st
import torch
import torchaudio
import os
import tempfile
import argbind
from pathlib import Path

# Vampnet / Audiotools imports
import audiotools as at
from audiotools import AudioSignal
from vampnet.interface import Interface

# Configure Streamlit page for production UI
st.set_page_config(
    page_title="VampNet Audio Generation",
    page_icon="🧛",
    layout="wide",
    initial_sidebar_state="expanded"
)

@st.cache_resource(show_spinner="Initializing VampNet Model Architecture...")
def load_vampnet_model():
    """
    Loads the VampNet interface securely and caches it across Streamlit reruns.
    It automatically downloads the required default checkpoints via Interface.core().
    """
    # Initialize argbind for VampNet's internal argument parser
    argbind.parse_args()
    
    # Initialize the core interface
    interface = Interface.core()
    
    # Check for hardware acceleration (CUDA/MPS) and fall back to CPU (Streamlit Cloud default)
    if torch.cuda.is_available():
        interface.to("cuda")
    elif hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():
        interface.to("mps")
    else:
        interface.to("cpu")
        
    return interface

def process_audio(interface, audio_bytes, target_duration, loop_mode, num_steps, temperature):
    """
    Core production inference function for VampNet
    """
    # Create temp file for the uploaded input audio
    with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as fp:
        fp.write(audio_bytes)
        temp_input_path = fp.name

    out_temp_path = None

    try:
        # Load audio signal via descript-audiotools
        signal = AudioSignal(temp_input_path)
        
        # Ensure audio matches VampNet's expected codec sample rate
        signal.resample(interface.codec.sample_rate)
        if signal.num_channels > 1:
            signal.to_mono()

        # Run model inference
        with torch.no_grad():
            output_signal = interface.vamp(
                signal=signal,
                duration=target_duration,
                num_steps=num_steps,
                temperature=temperature,
                return_signal=True,
                loop=loop_mode
            )
            
        # Save output to a new temporary file
        out_temp = tempfile.NamedTemporaryFile(delete=False, suffix=".wav")
        output_signal.write(out_temp.name)
        out_temp_path = out_temp.name
        
        # Read generated bytes to pass back to UI
        with open(out_temp_path, "rb") as out_fp:
            final_audio_bytes = out_fp.read()
            
        return final_audio_bytes
        
    finally:
        # Strict cleanup of temporary files to prevent storage leaks on the server
        if os.path.exists(temp_input_path):
            os.remove(temp_input_path)
        if out_temp_path and os.path.exists(out_temp_path):
            os.remove(out_temp_path)


def main():
    st.title("🧛 VampNet: Generative Audio Looping & Variations")
    st.markdown("Upload an audio sample and let VampNet extend, loop, or creatively modify it using masked acoustic token modeling.")

    # Load model and handle initialization errors gracefully
    try:
        interface = load_vampnet_model()
    except Exception as e:
        st.error(f"Failed to load VampNet model. Error: {str(e)}")
        st.stop()

    # Sidebar configuration parameters
    with st.sidebar:
        st.header("Generation Parameters")
        target_duration = st.slider("Target Duration (seconds)", min_value=1.0, max_value=30.0, value=10.0, step=0.5)
        num_steps = st.slider("Denoising Steps (Quality vs Speed)", min_value=10, max_value=150, value=36, step=2)
        temperature = st.slider("Temperature (Creativity)", min_value=0.1, max_value=2.0, value=1.0, step=0.1)
        loop_mode = st.checkbox("Loop Mode (Seamlessly tile audio)", value=False)
        
        st.markdown("---")
        st.info("Operating on: **CPU**" if not torch.cuda.is_available() else "Operating on: **CUDA GPU**")

    # Layout for Input/Output
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("1. Input Audio")
        uploaded_file = st.file_uploader("Upload reference audio", type=['wav', 'mp3', 'flac', 'ogg'])
        
        if uploaded_file is not None:
            input_audio_bytes = uploaded_file.read()
            st.audio(input_audio_bytes)

    with col2:
        st.subheader("2. Generate Output")
        generate_btn = st.button("Generate Audio 🚀", type="primary", use_container_width=True, disabled=(uploaded_file is None))
        
        if generate_btn and uploaded_file is not None:
            with st.spinner("VampNet is generating... (this may take a moment on CPU)"):
                try:
                    # Execute generation
                    output_bytes = process_audio(
                        interface=interface,
                        audio_bytes=input_audio_bytes,
                        target_duration=target_duration,
                        loop_mode=loop_mode,
                        num_steps=num_steps,
                        temperature=temperature
                    )
                    
                    st.success("Generation Complete!")
                    st.audio(output_bytes, format='audio/wav')
                    
                    st.download_button(
                        label="Download Output WAV",
                        data=output_bytes,
                        file_name="vampnet_output.wav",
                        mime="audio/wav",
                        use_container_width=True
                    )
                    
                except Exception as e:
                    st.error(f"An error occurred during generation: {str(e)}")

if __name__ == "__main__":
    main()
